### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by RV7PR** [thirtybees/postnl-api-php#38] opened 2021-04-29 07:23 UTC
**Exception:**
Argument 1 passed to GuzzleHttp\Psr7\Message::toString() must implement interface Psr\Http\Message\MessageInterface, null given, called in /vendor/firstred/postnl-api-php/src/HttpClient/CurlClient.php on line 178

**Notice:**
Undefined index: NL-0
/vendor/firstred/postnl-api-php/src/HttpClient/CurlClient.php:178

**Comment by firstred** [comment] 2021-04-29 18:12
Thanks for opening this issue! I think I have found the cause.

The cURL client doesn't add pending requests like the other clients do. I'll run a couple of tests to see if restoring that fixes the problem.

**Comment by firstred** [comment] 2021-04-29 18:13
You could fix it right now by installing Guzzle:

`composer require guzzlehttp/guzzle`

**Comment by firstred** [comment] 2021-04-29 19:15
Steps to reproduce the issue with `v1.3.2`:

```php
$postnl->getHttpClient()->addOrUpdateRequest('NL-0', $singleRequest);

$responses = $postnl->getHttpClient()->doRequests(['NL-1' => $anotherSingleRequest]);
```

**Comment by firstred** [comment] 2021-04-29 19:16
Confirmed to be fixed with https://github.com/firstred/postnl-api-php/commit/0873386e8031e266f314349419096aee8b9e295b

Tests are still green, let's just go for it! New release coming up.

**Comment by firstred** [comment] 2021-04-29 19:18
A new version, `v1.3.3`, has just been released.

**Comment by RV7PR** [comment] 2021-04-30 07:28
> You could fix it right now by installing Guzzle:
> 
> `composer require guzzlehttp/guzzle`

Well thats what i was wondering, i have guzzle installed so why was it using curl in the first place?🤔

**Comment by firstred** [comment] 2021-05-03 17:36
I think the problem lies in using the `version_compare` function. I just noticed that Guzzle stopped using version numbers separated by dots, which makes the `version_compare` check fail, due to this behavior:
https://www.php.net/manual/en/function.version-compare.php#89416

This can be solved by adding a custom function to compare Guzzle versions. I'll see what I can do.

**Comment by firstred** [comment] 2021-05-04 16:00
That seemed to do the trick.`v1.3.4` coming up...

**Closed as completed** 2021-12-30 02:23 UTC
